import type {
  Achievement,
  Application,
  AttendanceRecord,
  AuditEntry,
  Company,
  CompanyFeedback,
  Drive,
  Faculty,
  Internship,
  InternshipDocument,
  Interview,
  Message,
  Milestone,
  Notification,
  SelfPlacement,
  Student,
  Thread,
  WeeklyReport,
} from './types'

export const seedStudents: Student[] = [
  {
    id: 's1',
    name: 'Aarav Sharma',
    email: 'aarav.sharma@college.edu',
    password: 'password123',
    enrollment: 'EN21CS001',
    branch: 'Computer Science',
    cgpa: 8.7,
    backlogs: 0,
    passingYear: 2026,
    skills: ['React', 'Node.js', 'SQL'],
    certifications: ['AWS Cloud Practitioner'],
    phone: '+91 98220 11001',
    locationPreference: 'any',
    resumeUploaded: true,
    idDocsUploaded: true,
    status: 'approved',
    facultyId: 'f1',
  },
  {
    id: 's2',
    name: 'Priya Patel',
    email: 'priya.patel@college.edu',
    password: 'password123',
    enrollment: 'EN21CS014',
    branch: 'Computer Science',
    cgpa: 9.1,
    backlogs: 0,
    passingYear: 2026,
    skills: ['Python', 'ML', 'Data Analysis', 'Pandas'],
    certifications: ['Google Data Analytics'],
    phone: '+91 98220 11014',
    locationPreference: 'local',
    resumeUploaded: true,
    idDocsUploaded: true,
    status: 'approved',
    facultyId: 'f1',
  },
  {
    id: 's3',
    name: 'Rohan Verma',
    email: 'rohan.verma@college.edu',
    password: 'password123',
    enrollment: 'EN21EC022',
    branch: 'Electronics',
    cgpa: 7.2,
    backlogs: 2,
    passingYear: 2026,
    skills: ['Embedded C', 'IoT'],
    certifications: [],
    phone: '+91 98220 11022',
    locationPreference: 'outstation',
    resumeUploaded: true,
    idDocsUploaded: true,
    status: 'approved',
    facultyId: 'f2',
    atRisk: true,
  },
  {
    id: 's4',
    name: 'Sneha Iyer',
    email: 'sneha.iyer@college.edu',
    password: 'password123',
    enrollment: 'EN21ME010',
    branch: 'Mechanical',
    cgpa: 8.0,
    backlogs: 0,
    passingYear: 2026,
    skills: ['AutoCAD', 'SolidWorks'],
    certifications: ['NPTEL Machine Design'],
    phone: '+91 98220 11010',
    locationPreference: 'local',
    resumeUploaded: false,
    idDocsUploaded: true,
    status: 'approved',
    facultyId: 'f2',
  },
  {
    id: 's5',
    name: 'Kabir Singh',
    email: 'kabir.singh@college.edu',
    password: 'password123',
    enrollment: 'EN22CS031',
    branch: 'Computer Science',
    cgpa: 6.9,
    backlogs: 1,
    passingYear: 2027,
    skills: ['Java', 'Spring'],
    certifications: [],
    phone: '',
    locationPreference: 'any',
    resumeUploaded: true,
    idDocsUploaded: false,
    status: 'pending',
    facultyId: 'f1',
  },
  {
    id: 's6',
    name: 'Ananya Rao',
    email: 'ananya.rao@college.edu',
    password: 'password123',
    enrollment: 'EN22IT005',
    branch: 'Information Technology',
    cgpa: 8.4,
    backlogs: 0,
    passingYear: 2027,
    skills: ['UI/UX', 'Figma', 'React'],
    certifications: ['Google UX Design'],
    phone: '+91 98220 11005',
    locationPreference: 'local',
    resumeUploaded: true,
    idDocsUploaded: true,
    status: 'pending',
    facultyId: 'f1',
  },
  {
    id: 's7',
    name: 'Dev Mehta',
    email: 'dev.mehta@college.edu',
    password: 'password123',
    enrollment: 'EN21CS044',
    branch: 'Computer Science',
    cgpa: 7.8,
    backlogs: 0,
    passingYear: 2026,
    skills: ['Go', 'Docker', 'Kubernetes'],
    certifications: ['CKAD'],
    phone: '+91 98220 11044',
    locationPreference: 'outstation',
    resumeUploaded: true,
    idDocsUploaded: true,
    status: 'rejected',
    blockReason: 'ID document mismatch — re-upload requested',
    facultyId: 'f2',
  },
  {
    id: 's8',
    name: 'Isha Kulkarni',
    email: 'isha.kulkarni@college.edu',
    password: 'password123',
    enrollment: 'EN21CS050',
    branch: 'Computer Science',
    cgpa: 9.3,
    backlogs: 0,
    passingYear: 2026,
    skills: ['C++', 'Algorithms', 'React', 'TypeScript'],
    certifications: [],
    phone: '+91 98220 11050',
    locationPreference: 'any',
    resumeUploaded: true,
    idDocsUploaded: true,
    status: 'approved',
    facultyId: 'f1',
  },
]

export const seedCompanies: Company[] = [
  {
    id: 'c1',
    name: 'TechNova Systems',
    email: 'hr@technova.example.com',
    password: 'password123',
    industry: 'Software',
    website: 'https://technova.example.com',
    hrName: 'Meera Joshi',
    hrEmail: 'hr@technova.example.com',
    location: 'Pune',
    about: 'Product engineering company building SaaS platforms for logistics and retail.',
    certificateUploaded: true,
    status: 'approved',
  },
  {
    id: 'c2',
    name: 'DataForge Analytics',
    email: 'talent@dataforge.example.com',
    password: 'password123',
    industry: 'Data & AI',
    website: 'https://dataforge.example.com',
    hrName: 'Arjun Nair',
    hrEmail: 'talent@dataforge.example.com',
    location: 'Bengaluru',
    about: 'Analytics consultancy delivering ML pipelines and BI dashboards for enterprises.',
    certificateUploaded: true,
    status: 'approved',
  },
  {
    id: 'c3',
    name: 'MechWorks Industries',
    email: 'careers@mechworks.example.com',
    password: 'password123',
    industry: 'Manufacturing',
    website: 'https://mechworks.example.com',
    hrName: 'Sunita Desai',
    hrEmail: 'careers@mechworks.example.com',
    location: 'Pune',
    about: 'Precision manufacturing and industrial automation solutions.',
    certificateUploaded: true,
    status: 'approved',
  },
  {
    id: 'c4',
    name: 'CloudPeak Labs',
    email: 'people@cloudpeak.example.com',
    password: 'password123',
    industry: 'Cloud Infrastructure',
    website: 'https://cloudpeak.example.com',
    hrName: 'Vikram Shah',
    hrEmail: 'people@cloudpeak.example.com',
    location: 'Remote',
    about: 'Cloud-native tooling startup focused on developer experience.',
    certificateUploaded: true,
    status: 'pending',
  },
  {
    id: 'c5',
    name: 'FinEdge Capital',
    email: 'hr@finedge.example.com',
    password: 'password123',
    industry: 'FinTech',
    website: 'https://finedge.example.com',
    hrName: 'Ritu Malhotra',
    hrEmail: 'hr@finedge.example.com',
    location: 'Mumbai',
    about: 'Digital lending and payments platform.',
    certificateUploaded: false,
    status: 'pending',
    addedByStudentId: 's1',
  },
]

const daysFromNow = (d: number) => {
  const dt = new Date()
  dt.setDate(dt.getDate() + d)
  return dt.toISOString().slice(0, 10)
}

export const seedDrives: Drive[] = [
  {
    id: 'd1',
    companyId: 'c1',
    title: 'Frontend Engineering Intern',
    description:
      'Work with the platform team on React-based dashboards, design systems, and performance tuning. You will ship production features under mentorship.',
    skills: ['React', 'TypeScript', 'CSS'],
    field: 'Software',
    location: 'Pune',
    workMode: 'hybrid',
    stipend: 20000,
    durationWeeks: 12,
    openings: 3,
    minCgpa: 7.5,
    maxBacklogs: 0,
    passingYears: [2026],
    requiredSkills: ['React'],
    requiredCertifications: [],
    locationFilter: 'any',
    fieldFilter: 'Computer Science',
    anyoneCanApply: false,
    openDate: daysFromNow(-20),
    deadline: daysFromNow(10),
    startDate: daysFromNow(30),
    endDate: daysFromNow(114),
    status: 'open',
  },
  {
    id: 'd2',
    companyId: 'c2',
    title: 'Data Science Intern',
    description:
      'Build and evaluate ML models on real client datasets. Exposure to feature engineering, model monitoring, and stakeholder reporting.',
    skills: ['Python', 'Pandas', 'ML'],
    field: 'Data & AI',
    location: 'Bengaluru',
    workMode: 'onsite',
    stipend: 25000,
    durationWeeks: 16,
    openings: 2,
    minCgpa: 8.0,
    maxBacklogs: 0,
    passingYears: [2026],
    requiredSkills: ['Python', 'ML'],
    requiredCertifications: [],
    locationFilter: 'any',
    fieldFilter: 'Computer Science',
    anyoneCanApply: false,
    openDate: daysFromNow(-15),
    deadline: daysFromNow(7),
    startDate: daysFromNow(25),
    endDate: daysFromNow(137),
    status: 'open',
  },
  {
    id: 'd3',
    companyId: 'c1',
    title: 'Backend Engineering Intern',
    description:
      'Design REST APIs and background jobs in Node.js. Work on data models, caching, and observability with the core services team.',
    skills: ['Node.js', 'SQL', 'Redis'],
    field: 'Software',
    location: 'Pune',
    workMode: 'onsite',
    stipend: 22000,
    durationWeeks: 12,
    openings: 2,
    minCgpa: 7.0,
    maxBacklogs: 1,
    passingYears: [2026],
    requiredSkills: ['Node.js'],
    requiredCertifications: [],
    locationFilter: 'local',
    fieldFilter: 'Computer Science',
    anyoneCanApply: false,
    openDate: daysFromNow(-25),
    deadline: daysFromNow(5),
    startDate: daysFromNow(20),
    endDate: daysFromNow(104),
    status: 'open',
  },
  {
    id: 'd4',
    companyId: 'c3',
    title: 'Design Engineering Intern',
    description:
      'CAD modelling, tolerance analysis, and shop-floor exposure for automation fixtures. Mentored by senior design engineers.',
    skills: ['AutoCAD', 'SolidWorks'],
    field: 'Mechanical',
    location: 'Pune',
    workMode: 'onsite',
    stipend: 15000,
    durationWeeks: 8,
    openings: 4,
    minCgpa: 7.0,
    maxBacklogs: 0,
    passingYears: [2026, 2027],
    requiredSkills: ['AutoCAD'],
    requiredCertifications: ['NPTEL Machine Design'],
    locationFilter: 'local',
    fieldFilter: 'Mechanical',
    anyoneCanApply: false,
    openDate: daysFromNow(-10),
    deadline: daysFromNow(14),
    startDate: daysFromNow(35),
    endDate: daysFromNow(91),
    status: 'open',
  },
  {
    id: 'd5',
    companyId: 'c2',
    title: 'Business Analyst Intern',
    description:
      'Support client engagements with dashboarding, requirement notes, and data storytelling. Open to all branches.',
    skills: ['Excel', 'SQL', 'Communication'],
    field: 'Analytics',
    location: 'Remote',
    workMode: 'remote',
    stipend: 12000,
    durationWeeks: 10,
    openings: 5,
    minCgpa: 0,
    maxBacklogs: 99,
    passingYears: [],
    requiredSkills: [],
    requiredCertifications: [],
    locationFilter: 'any',
    fieldFilter: 'Any',
    anyoneCanApply: true,
    openDate: daysFromNow(-5),
    deadline: daysFromNow(20),
    startDate: daysFromNow(40),
    endDate: daysFromNow(110),
    status: 'open',
  },
  {
    id: 'd6',
    companyId: 'c3',
    title: 'IoT Systems Intern',
    description:
      'Firmware and sensor integration for factory telemetry. Hands-on with embedded C and MQTT pipelines.',
    skills: ['Embedded C', 'IoT', 'MQTT'],
    field: 'Electronics',
    location: 'Pune',
    workMode: 'onsite',
    stipend: 18000,
    durationWeeks: 12,
    openings: 2,
    minCgpa: 7.5,
    maxBacklogs: 0,
    passingYears: [2026],
    requiredSkills: ['Embedded C', 'IoT'],
    requiredCertifications: [],
    locationFilter: 'any',
    fieldFilter: 'Electronics',
    anyoneCanApply: false,
    openDate: daysFromNow(-30),
    deadline: daysFromNow(-2),
    startDate: daysFromNow(15),
    endDate: daysFromNow(99),
    status: 'closed',
  },
]

export const seedApplications: Application[] = [
  {
    id: 'a1',
    driveId: 'd1',
    studentId: 's8',
    status: 'shortlisted',
    appliedAt: daysFromNow(-12),
    history: [
      { status: 'applied', at: daysFromNow(-12) },
      { status: 'under_review', at: daysFromNow(-9) },
      { status: 'shortlisted', at: daysFromNow(-6) },
    ],
  },
  {
    id: 'a2',
    driveId: 'd2',
    studentId: 's2',
    status: 'interview_scheduled',
    appliedAt: daysFromNow(-10),
    history: [
      { status: 'applied', at: daysFromNow(-10) },
      { status: 'under_review', at: daysFromNow(-8) },
      { status: 'shortlisted', at: daysFromNow(-5) },
      { status: 'interview_scheduled', at: daysFromNow(-2) },
    ],
  },
  {
    id: 'a3',
    driveId: 'd3',
    studentId: 's1',
    status: 'selected',
    appliedAt: daysFromNow(-40),
    history: [
      { status: 'applied', at: daysFromNow(-40) },
      { status: 'under_review', at: daysFromNow(-36) },
      { status: 'shortlisted', at: daysFromNow(-32) },
      { status: 'interview_scheduled', at: daysFromNow(-28) },
      { status: 'selected', at: daysFromNow(-24) },
    ],
  },
  {
    id: 'a4',
    driveId: 'd1',
    studentId: 's1',
    status: 'under_review',
    appliedAt: daysFromNow(-4),
    history: [
      { status: 'applied', at: daysFromNow(-4) },
      { status: 'under_review', at: daysFromNow(-2) },
    ],
  },
  {
    id: 'a5',
    driveId: 'd5',
    studentId: 's3',
    status: 'applied',
    appliedAt: daysFromNow(-1),
    history: [{ status: 'applied', at: daysFromNow(-1) }],
  },
  {
    id: 'a6',
    driveId: 'd2',
    studentId: 's8',
    status: 'rejected',
    appliedAt: daysFromNow(-9),
    rejectReason: 'Profile did not match required ML depth for this cohort.',
    history: [
      { status: 'applied', at: daysFromNow(-9) },
      { status: 'under_review', at: daysFromNow(-7) },
      { status: 'rejected', at: daysFromNow(-4) },
    ],
  },
]

export const seedInterviews: Interview[] = [
  {
    id: 'i1',
    applicationId: 'a2',
    date: daysFromNow(3),
    time: '11:00',
    mode: 'online',
    linkOrVenue: 'https://meet.example.com/dataforge-priya',
    panel: 'Arjun Nair (HR), Kavya S (Lead DS)',
    instructions: 'Keep your college ID ready. 45 min technical + 15 min HR.',
    acknowledged: false,
  },
]

export const seedInternships: Internship[] = [
  {
    id: 'n1',
    studentId: 's1',
    companyId: 'c1',
    driveId: 'd3',
    role: 'Backend Engineering Intern',
    type: 'college',
    startDate: daysFromNow(-21),
    endDate: daysFromNow(63),
    status: 'active',
    ppoStatus: 'none',
  },
  {
    id: 'n2',
    studentId: 's8',
    companyId: 'c1',
    role: 'Frontend Engineering Intern (2025 cycle)',
    location: 'Bengaluru',
    type: 'college',
    startDate: daysFromNow(-210),
    endDate: daysFromNow(-126),
    status: 'completed',
    finalEvaluation:
      'Outstanding intern. Shipped the design-system migration end to end and mentored a junior intern in the final month. Recommended for a pre-placement offer.',
    ppoStatus: 'accepted',
    ppoPackage: 1200000,
    ppoNote: 'Converted to full-time SDE-1 starting after graduation.',
  },
  {
    id: 'n3',
    studentId: 's3',
    companyId: 'c3',
    role: 'IoT Systems Intern (2025 cycle)',
    location: 'Nashik',
    type: 'college',
    startDate: daysFromNow(-190),
    endDate: daysFromNow(-106),
    status: 'completed',
    finalEvaluation:
      'Completed the telemetry firmware task with guidance. Attendance was inconsistent in the middle weeks.',
    ppoStatus: 'none',
  },
]

export const seedDocuments: InternshipDocument[] = [
  {
    id: 'doc1',
    internshipId: 'n1',
    kind: 'offer_letter',
    fileName: 'technova-offer-aarav.pdf',
    uploadedBy: 'company',
    uploadedAt: daysFromNow(-30),
    status: 'verified',
    verifyCode: 'ITK-N1-OFR-4821',
  },
  {
    id: 'doc2',
    internshipId: 'n1',
    kind: 'joining_letter',
    fileName: 'technova-joining-aarav.pdf',
    uploadedBy: 'company',
    uploadedAt: daysFromNow(-22),
    status: 'verified',
    verifyCode: 'ITK-N1-JOI-9134',
  },
  {
    id: 'doc3',
    internshipId: 'n1',
    kind: 'acceptance',
    fileName: 'acceptance-signed-aarav.pdf',
    uploadedBy: 'student',
    uploadedAt: daysFromNow(-28),
    status: 'uploaded',
  },
  { id: 'doc4', internshipId: 'n1', kind: 'completion_certificate', status: 'not_uploaded' },
  { id: 'doc5', internshipId: 'n1', kind: 'ppo_letter', status: 'not_uploaded' },
  {
    id: 'doc6',
    internshipId: 'n2',
    kind: 'offer_letter',
    fileName: 'technova-offer-isha.pdf',
    uploadedBy: 'company',
    uploadedAt: daysFromNow(-218),
    status: 'verified',
    verifyCode: 'ITK-N2-OFR-2210',
  },
  {
    id: 'doc7',
    internshipId: 'n2',
    kind: 'joining_letter',
    fileName: 'technova-joining-isha.pdf',
    uploadedBy: 'company',
    uploadedAt: daysFromNow(-211),
    status: 'verified',
    verifyCode: 'ITK-N2-JOI-7745',
  },
  {
    id: 'doc8',
    internshipId: 'n2',
    kind: 'acceptance',
    fileName: 'acceptance-signed-isha.pdf',
    uploadedBy: 'student',
    uploadedAt: daysFromNow(-215),
    status: 'verified',
  },
  {
    id: 'doc9',
    internshipId: 'n2',
    kind: 'completion_certificate',
    fileName: 'technova-completion-isha.pdf',
    uploadedBy: 'company',
    uploadedAt: daysFromNow(-124),
    status: 'verified',
    verifyCode: 'ITK-N2-CMP-5063',
  },
  {
    id: 'doc10',
    internshipId: 'n2',
    kind: 'ppo_letter',
    fileName: 'technova-ppo-isha.pdf',
    uploadedBy: 'company',
    uploadedAt: daysFromNow(-120),
    status: 'verified',
    verifyCode: 'ITK-N2-PPO-8890',
  },
  {
    id: 'doc11',
    internshipId: 'n3',
    kind: 'offer_letter',
    fileName: 'mechworks-offer-rohan.pdf',
    uploadedBy: 'company',
    uploadedAt: daysFromNow(-198),
    status: 'verified',
    verifyCode: 'ITK-N3-OFR-3312',
  },
  { id: 'doc12', internshipId: 'n3', kind: 'joining_letter', status: 'not_uploaded' },
  { id: 'doc13', internshipId: 'n3', kind: 'acceptance', status: 'not_uploaded' },
  {
    id: 'doc14',
    internshipId: 'n3',
    kind: 'completion_certificate',
    fileName: 'mechworks-completion-rohan.pdf',
    uploadedBy: 'company',
    uploadedAt: daysFromNow(-104),
    status: 'uploaded',
  },
  { id: 'doc15', internshipId: 'n3', kind: 'ppo_letter', status: 'not_uploaded' },
]

export const seedWeeklyReports: WeeklyReport[] = [
  {
    id: 'w1',
    internshipId: 'n1',
    week: 1,
    workDone: 'Onboarding, local environment setup, fixed two starter bugs in the orders API.',
    skillsLearned: 'Express middleware patterns, PR review workflow',
    hours: 38,
    evidenceName: 'week1-summary.pdf',
    status: 'faculty_reviewed',
  },
  {
    id: 'w2',
    internshipId: 'n1',
    week: 2,
    workDone: 'Implemented pagination for the orders endpoint and wrote integration tests.',
    skillsLearned: 'Cursor pagination, supertest',
    hours: 40,
    evidenceName: 'week2-summary.pdf',
    status: 'company_approved',
  },
  {
    id: 'w3',
    internshipId: 'n1',
    week: 3,
    workDone: 'Started the Redis caching layer for product lookups; drafted the design note.',
    skillsLearned: 'Cache invalidation strategies',
    hours: 36,
    status: 'submitted',
  },
]

export const seedAttendance: AttendanceRecord[] = [
  {
    internshipId: 'n1',
    workingDays: 15,
    present: 14,
    absent: 1,
    leave: 0,
    lastMarkedDate: daysFromNow(-1),
    entries: [
      { date: daysFromNow(-1), status: 'present' },
      { date: daysFromNow(-2), status: 'present' },
      { date: daysFromNow(-3), status: 'present' },
      { date: daysFromNow(-4), status: 'absent' },
    ],
  },
  {
    internshipId: 'n2',
    workingDays: 60,
    present: 58,
    absent: 1,
    leave: 1,
    lastMarkedDate: daysFromNow(-120),
  },
  {
    internshipId: 'n3',
    workingDays: 60,
    present: 44,
    absent: 12,
    leave: 4,
    lastMarkedDate: daysFromNow(-100),
  },
]

export const seedMilestones: Milestone[] = [
  {
    id: 'm1',
    internshipId: 'n1',
    title: 'Orders API pagination shipped',
    dueDate: daysFromNow(-7),
    status: 'completed',
    companyRemark: 'Delivered on time with tests.',
    facultyRemark: 'Good documentation.',
  },
  {
    id: 'm2',
    internshipId: 'n1',
    title: 'Redis caching layer',
    dueDate: daysFromNow(7),
    status: 'in_progress',
    companyRemark: 'Design note approved.',
  },
  {
    id: 'm3',
    internshipId: 'n1',
    title: 'Final project presentation',
    dueDate: daysFromNow(56),
    status: 'pending',
  },
]

export const seedFeedback: CompanyFeedback[] = [
  {
    id: 'fb1',
    internshipId: 'n1',
    week: 1,
    attendance: 5,
    workQuality: 4,
    communication: 4,
    technical: 4,
    comments: 'Quick ramp-up, asks good questions.',
  },
  {
    id: 'fb2',
    internshipId: 'n1',
    week: 2,
    attendance: 5,
    workQuality: 5,
    communication: 4,
    technical: 5,
    comments: 'Pagination work was production quality.',
  },
]

export const seedSelfPlacements: SelfPlacement[] = [
  {
    id: 'sp1',
    studentId: 's4',
    companyName: 'Precision Auto Components',
    role: 'CAD Intern',
    location: 'Jalgaon',
    startDate: daysFromNow(10),
    endDate: daysFromNow(80),
    stipend: 10000,
    offerLetterUploaded: true,
    joiningLetterUploaded: false,
    certificateUploaded: false,
    nocUploaded: true,
    status: 'pending',
  },
]

export const seedAchievements: Achievement[] = [
  {
    id: 'ac1',
    studentId: 's2',
    type: 'hackathon',
    title: 'Winner — Smart India Hackathon (Software Edition)',
    date: daysFromNow(-60),
    evidenceName: 'sih-certificate.pdf',
    status: 'verified',
  },
  {
    id: 'ac2',
    studentId: 's1',
    type: 'certification',
    title: 'AWS Cloud Practitioner',
    date: daysFromNow(-30),
    evidenceName: 'aws-ccp.pdf',
    status: 'pending',
  },
  {
    id: 'ac3',
    studentId: 's8',
    type: 'paper',
    title: 'Paper presentation: Graph algorithms for route optimization',
    date: daysFromNow(-14),
    evidenceName: 'paper-slides.pdf',
    status: 'pending',
  },
]

export const seedThreads: Thread[] = [
  {
    id: 't1',
    subject: 'Resume verification query',
    participants: ['student', 'admin'],
    participantIds: ['s1', 'admin1'],
    participantNames: 'Aarav Sharma ↔ T&P Cell',
    unreadFor: ['admin'],
  },
  {
    id: 't2',
    subject: 'Drive eligibility relaxation request',
    participants: ['company', 'admin'],
    participantIds: ['c1', 'admin1'],
    participantNames: 'TechNova Systems ↔ T&P Cell',
    unreadFor: ['admin'],
  },
  {
    id: 't3',
    subject: 'Weekly report format',
    participants: ['student', 'faculty'],
    participantIds: ['s1', 'f1'],
    participantNames: 'Aarav Sharma ↔ Prof. R. Kulkarni',
    unreadFor: ['student'],
  },
  {
    id: 't4',
    subject: 'Self-placement verification query',
    participants: ['student', 'faculty'],
    participantIds: ['s2', 'f1'],
    participantNames: 'Priya Patel ↔ Prof. R. Kulkarni',
    unreadFor: [],
  },
]

export const seedMessages: Message[] = [
  {
    id: 'msg1',
    threadId: 't1',
    fromRole: 'student',
    fromUserId: 's1',
    fromName: 'Aarav Sharma',
    body: 'Hello, I updated my resume last week. Could you confirm it has been re-verified for the TechNova drive?',
    at: daysFromNow(-2),
  },
  {
    id: 'msg2',
    threadId: 't2',
    fromRole: 'company',
    fromUserId: 'c1',
    fromName: 'TechNova Systems',
    body: 'We would like to relax the CGPA cutoff to 7.0 for the Frontend drive. Please advise.',
    at: daysFromNow(-1),
  },
  {
    id: 'msg3',
    threadId: 't3',
    fromRole: 'faculty',
    fromUserId: 'f1',
    fromName: 'Prof. R. Kulkarni',
    body: 'Please include evidence uploads for week 3 onward. The format sheet is attached.',
    at: daysFromNow(-1),
    attachmentName: 'report-format.pdf',
  },
  {
    id: 'msg4',
    threadId: 't4',
    fromRole: 'student',
    fromUserId: 's2',
    fromName: 'Priya Patel',
    body: 'Good morning Professor, I have uploaded my self-placement offer letter for review.',
    at: daysFromNow(-1),
  },
]

export const seedNotifications: Notification[] = [
  {
    id: 'nt1',
    forRole: 'student',
    title: 'Interview scheduled',
    body: 'DataForge Analytics scheduled your interview for the Data Science Intern role.',
    at: daysFromNow(-2),
    read: false,
  },
  {
    id: 'nt2',
    forRole: 'admin',
    title: 'New company registration',
    body: 'CloudPeak Labs submitted registration documents for verification.',
    at: daysFromNow(-3),
    read: false,
  },
  {
    id: 'nt3',
    forRole: 'faculty',
    title: 'Weekly report submitted',
    body: 'Aarav Sharma submitted the week 3 report for review.',
    at: daysFromNow(-1),
    read: false,
  },
  {
    id: 'nt4',
    forRole: 'company',
    title: 'New applicant',
    body: 'Isha Kulkarni applied to Frontend Engineering Intern.',
    at: daysFromNow(-4),
    read: true,
  },
]

export const seedAudit: AuditEntry[] = [
  {
    id: 'au1',
    actor: 'Admin (T&P Cell)',
    action: 'Approved student',
    target: 'Aarav Sharma (EN21CS001)',
    at: daysFromNow(-45),
  },
  {
    id: 'au2',
    actor: 'Admin (T&P Cell)',
    action: 'Approved company',
    target: 'TechNova Systems',
    at: daysFromNow(-42),
  },
  {
    id: 'au3',
    actor: 'Admin (T&P Cell)',
    action: 'Rejected student',
    target: 'Dev Mehta (EN21CS044)',
    reason: 'ID document mismatch — re-upload requested',
    at: daysFromNow(-8),
  },
  {
    id: 'au4',
    actor: 'Prof. R. Kulkarni',
    action: 'Reviewed weekly report',
    target: 'Aarav Sharma — Week 1',
    at: daysFromNow(-14),
  },
]

export const faculty: Faculty[] = [
  {
    id: 'f1',
    name: 'Prof. R. Kulkarni',
    email: 'faculty@college.edu',
    department: 'Computer Science',
    designation: 'Associate Professor & Mentor',
    password: 'faculty123',
    phone: '+91 98220 55001',
  },
  {
    id: 'f2',
    name: 'Prof. S. Deshpande',
    email: 's.deshpande@college.edu',
    department: 'Mechanical & Electronics',
    designation: 'Assistant Professor & Mentor',
    password: 'password123',
    phone: '+91 98220 55002',
  },
]
